server:
    port: 8082
spring:
    datasource:
        driver-class-name: org.h2.Driver
        password: 123
        url: jdbc:h2:mem:dcbapp
        username: test
    h2:
        console:
            enabled: true
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
